name: container

on:
  push:
    #tags:
    #  - '*'
    branches:
      - feature/helm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        ref: '2.3.0'  

    - name: get version
      run: echo ::set-output name=APP_VERSION::${GITHUB_REF/refs\/tags\//}

    - name: init docker build
      uses: docker/setup-buildx-action@v1

    - name: login docker
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: publish container
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ghcr.io/weblyzard/inscriptis:v${{ env.APP_VERSION }}
          ghcr.io/weblyzard/inscriptis:latest
